### ISSUE TITLE
Dependabot alert on use of `guzzlehttp/psr7`

### ISSUE THREAD

**Issue by hayhurst** [usefulteam/jwt-auth#104]
<img width="954" alt="image" src="https://user-images.githubusercontent.com/15649917/235674939-c4cedeab-eb94-48e3-9290-90c138d2106d.png">

Could this be looked into?

**Comment by hayhurst** [comment]
Bump :(

**Comment by wavedeck** [comment]
@hayhurst since guzzlehttp is only used for unit testing, the vulnerability does not have an impact to the plugin security in itself.

For the mentioned exploit to be possible, an attacker would have to have access to the developers computer. But if that were the case, you’d have a completely different set of problems and exploiting guzzlehttp will be your absolute least of concerns

**Comment by sun** [comment]
@wavedeck Sounds great. :)  Would you like to create a PR that contains the necessary changes?

Just make sure that your branch of the PR really only contains the minimum necessary changes to address the issue.

**Comment by wavedeck** [comment]
@sun [this PR](https://github.com/usefulteam/jwt-auth/pull/112) should close that issue (and also prevent a possibly overlooked raise in the required PHP version)
