### ISSUE TITLE
Who manages the plugin on WordPress.org

### ISSUE THREAD

**Issue by dominic-ks** [usefulteam/jwt-auth#70]
Probably a question for @contactjavas, but just noting your recent comments that you haven't much time for this repo at present, I may be interested in becoming more active and I'm a heavy user of this plugin, but wanted to know who manages it on WordPress.org? 

I seem to remember a while ago there was a Discord or Slack for this as well? Or am I making that up?

**Comment by contactjavas** [comment]
Hi @pesseba , I've also just added you as a committer for this plugin in WordPress.org
I'm sorry for adding you without asking your permission first 😁

**Comment by pesseba** [comment]
Nice @contactjavas I'm glad to contribute with the plugin!

**Comment by sun** [comment]
Sorry for the late reply, everyone.  I don't have too much time for participating in the maintenance.  I'm mainly working on the plugin as part of the maintenance work for one of our projects.  My main interest is to keep the plugin stable and secure, because we're using it as a SSO for a larger production site to authenticate multiple native mobile apps against WordPress.

I think the suggested setup and adding more maintainers makes sense.  With this constellation, we could consider to enable the GitHub branch protection setting to only allow PRs to be merged when they have at least two approvals from maintainers.  What do you think?  If things get stalled too much, we can reduce it to one approval.

Apparently I don't have admin/maintain access to this GitHub repository yet, so I can't review the current settings.  @contactjavas Could you check the access settings?

**Comment by contactjavas** [comment]
Hi! I've just changed @sun , @pesseba , & @dominic-ks access from maintainer to admin :)

**Comment by contactjavas** [comment]
Hi! I've just changed @sun , @pesseba , & @dominic-ks access from maintainer to admin :)

**Comment by dominic-ks** [comment]
Hey @sun and @pesseba, obviously everyone can only do what they can do. Similarly I'm keen for things to stay stable and I think needing two approvals is a good idea. Then I think it'd just be good if things are straight as to when things are released on wp.org. I'm happy to do some of these things but don't necessarily want to take on the responsibility of solely deciding if something is ready for release for updates or not!

Perhaps we can have a channel on the Discord for us to discuss what we will do going forward?

**Comment by pesseba** [comment]
@dominic-ks sounds good a discord channel for development, We are using the issues to talk each other
